name: ridesharing
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.1.1
  geolocator: ^10.0.0
  google_map_polyline_new: ^0.3.0+2
  geocoding: ^2.1.0
  flutter_polyline_points: ^1.0.0
  google_places_flutter: ^2.0.6
  intl: ^0.18.1
  firebase_messaging: ^14.6.8
  url_launcher: ^6.1.14
  maps_launcher: ^2.2.0
  location: ^5.0.3
  flutter_launcher_icons: ^0.13.1
 
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true
  assets:
    - lib/images/

  