// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cDI8vQ9dxfqHw1K98-ICtejmqR_aA_0',
    appId: '1:1094424006770:web:9a41bcc7147b3f273272eb',
    messagingSenderId: '1094424006770',
    projectId: 'ride-sharing-app-de6eb',
    authDomain: 'ride-sharing-app-de6eb.firebaseapp.com',
    storageBucket: 'ride-sharing-app-de6eb.appspot.com',
    measurementId: 'G-SPQ735Z0GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HbEbRS3WvpDu1eglxNkjwiZq7f2wanc',
    appId: '1:1094424006770:android:504104aa00c48e463272eb',
    messagingSenderId: '1094424006770',
    projectId: 'ride-sharing-app-de6eb',
    storageBucket: 'ride-sharing-app-de6eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6UfylQdiJkeFCtQqkLOehCs7_xNGaUw',
    appId: '1:1094424006770:ios:3eb9bd8ba5d244293272eb',
    messagingSenderId: '1094424006770',
    projectId: 'ride-sharing-app-de6eb',
    storageBucket: 'ride-sharing-app-de6eb.appspot.com',
    iosClientId: '1094424006770-rm5s9v9g72sj0lkb09eio3o47kdsglfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridesharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6UfylQdiJkeFCtQqkLOehCs7_xNGaUw',
    appId: '1:1094424006770:ios:17eca94807312b283272eb',
    messagingSenderId: '1094424006770',
    projectId: 'ride-sharing-app-de6eb',
    storageBucket: 'ride-sharing-app-de6eb.appspot.com',
    iosClientId: '1094424006770-g08f3a6efbgaojdrdjd4joioh21hd7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridesharing.RunnerTests',
  );
}
